version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: radius-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: radius
      MYSQL_USER: radius
      MYSQL_PASSWORD: radius
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  freeradius:
    container_name: freeradius
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    restart: unless-stopped

volumes:
  mysql_data:
